pub mod animation;
pub mod app;
// pub mod barchart;
pub mod colophon;
pub mod flashcard;
pub mod footer;
pub mod home;
pub mod language_select;
pub mod nav;
pub mod retirement;
pub mod slideshow;
pub mod template;
pub mod translator;
